version: '3.8'

services:
  # Frontend - React con Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend

  # Backend - Node.js con Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://ju4nc4rrill00_db_user:HWltTYN58FEHwsxa@cluster0.p6a1o2n.mongodb.net/training-portal
      - JWT_SECRET=your_jwt_secret_key

  # MinIO para almacenamiento de archivos
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  # MailHog para pruebas de email
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongodb_data:
  minio_data: