version: '3.8'

services:
  # Frontend - React con Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy

  # Backend - Node.js con Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://ju4nc4rrill00_db_user:HWltTYN58FEHwsxa@cluster0.p6a1o2n.mongodb.net/training-portal
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # MinIO para almacenamiento de archivos
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  # MailHog para pruebas de email
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  frontend_node_modules:
  backend_node_modules:
  minio_data: